### ISSUE TITLE
Max line length corner case?

### ISSUE THREAD

**Issue by slacktracer** [prettier/prettier-atom#129]
_Prettier_ then _eslint --fix_ then _max-len_ error.

The following code is perfectly formatted by prettier alone but when eslint _--fixes_ it the maximum line length rule is violated.

```
module.exports = function(x) {
  const sortPlacesByDistance = function sortPlacesByDistance(place_a, place_b) {
    return place_a.distance - place_b.distance;
  };
  sortPlacesByDistance(x);
};
```

.eslintrc.js:
```
module.exports = {
  env: { es6: true, node: true },
  rules: {
    'max-len': [ 'error', 80 ],
    'space-before-function-paren': [ 'error', 'always' ]
  }
};
```

_--fixed_:
```
module.exports = function (x) {

  const sortPlacesByDistance = function sortPlacesByDistance (place_a, place_b) {

    return place_a.distance - place_b.distance;

  };
  sortPlacesByDistance(x);

};
```

Is it even fixable? I mean, it's the fix that breaks it.

Is it the definition of irony...?

**Comment by robwise** [comment]
@slacktracer It seems that your "before" code, although passing the line-length rule, would fail the `space-before-function-paren` rule. Enabling eslint fix adds the space and then causes the linelength validation to fail, but because eslint is run _after_ prettier, then prettier can't fix the linelength anymore. I'm not sure there's a real solution to this, but you may want to bring this up over at the [prettier-eslint](https://github.com/prettier/prettier-eslint) repo.

**Comment by slacktracer** [comment]
@robwise 

Sorry. It was not clear to me that this repo is not the one responsible for the eslint integration.

Thank you very much anyway.
