### ISSUE TITLE
Show parsing errors inline

### ISSUE THREAD

**Issue by gaearon** [prettier/prettier-atom#146]
I'm not sure if it's even possible, but another piece of feedback from using Prettier Atom with JS beginners is that the parser messages are a bit confusing. They appear as a popup and you have to spend mental energy mapping them back to your code. It would be amazing if the errors could be shown inline in code (does Atom have an error panel and APIs for adding errors to it?)

Apologies if this is out of scope, or very hard to implement.

**Comment by robwise** [comment]
We actually had already been discussing this as a possibility in another thread, but I forgot to make an issue, so thanks! I think we can use the stack trace to point back to the line similar to how flow or eslint do this when you have a parsing error:

![](https://cl.ly/0q3e1n3x1H3y/Image%202017-04-27%20at%205.18.57%20PM.png)

It will take some work, but I think it's worth it because apparently a lot of people who are not using eslint or flow rely on the output from prettier-atom to debug their parsing errors. It's a use case I did not expect but am happy to support.

**Comment by gaearon** [comment]
Yea, I can understand how this could initially seem out of scope, but it would be very handy.

**Comment by robwise** [comment]
@steelbrain Would I need (or do you suggest) that we use atom-linter for this? If yes, will I break the experience for users who did not already have the atom-linter package installed?

**Comment by steelbrain** [comment]
Hi @robwise 

I definitely think that showing syntax errors with Linter is the most seamless experience for the users. Tho you could only show it for people who already have it installed but I would recommend you use [`atom-package-deps`](https://www.npmjs.com/package/atom-package-deps) to ensure it's installed so the userbase has a consistent experience.

Because your package is going to be invoked independently instead of on-save, you could use the [`Indie Linter API v2`](http://steelbrain.me/linter/examples/indie-linter-v2.html). Though that way you'll have to remove messages for files that are closed in your package.

Let me know if I can be of further help!

**Comment by michaeljcalkins** [comment]
I don't think the popups are even needed.  The same error appears in my linter console.

<img width="1091" alt="screen shot 2017-06-22 at 11 35 12 am" src="https://user-images.githubusercontent.com/8272012/27449945-e2e3a916-573e-11e7-9dae-
c51ae6aadbd4.png">

**Comment by robwise** [comment]
Yeah I agree, I'm planning on switching to just using the linter and getting rid of the popup stuff. I just had to get through some of the earlier issues first, but this is the next thing on my list to implement.

**Comment by michaeljcalkins** [comment]
@robwise I just realized you had this option, what if it was just true by default?

https://github.com/prettier/prettier-atom/blob/master/src/config-schema.json#L6

<img width="497" alt="screen shot 2017-06-22 at 7 07 31 pm" src="https://user-images.githubusercontent.com/8272012/27463699-140f2b66-577e-11e7-89c7-5881ae04de41.png">

**Comment by robwise** [comment]
@michaeljcalkins Yeah, I keep that enabled myself. I'm worried that if it was true by default, and someone has a syntax error, they won't ever realize that the plugin is erroring. I'd rather have it on, and if they find it annoying, turn it off. Like I said, pretty soon I will switch to using the linter API/packages and we won't have this annoyance anymore.

**Comment by flockonus** [comment]
Hello!
Looking for some info. If i'm not using eslint on my project is there still a way to display errors on save?
Can't seem to find an option on the config or docs. Do i need some other config in Atom?

**Comment by darahak** [comment]
@flockonus I don't think this is related to ESLint. The `linter` package is just being used to display the errors.
Currently there is a bug with this. You can watch https://github.com/prettier/prettier-atom/issues/235 which seems related to your question.
