### ISSUE TITLE
Feature request: keyboard shortcut to save without formatting 

### ISSUE THREAD

**Issue by alekhurst** [prettier/prettier-atom#198]
First of all, this package is a godsend!

Wanted to bring up something that I have come across often when using it. I use the "format on save" option because 95% of the time this is my preferred behavior, but sometimes when I'm working on an html file, or migration file that only supports es5 syntax, I want to save without formatting.

I realize that I could disable format on save and use a keyboard shortcut to format, but not needing to format on save happens infrequently enough that this wouldn't be as efficient.

**Comment by robwise** [comment]
I think now that we have the ability to easily toggle format-on-save (either via a shortcut or clicking the checkmark in the lower-left corner of the screen), that is hopefully good enough, as I'm not sure there's really a way around this otherwise. I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
