### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by darahak** [prettier/prettier-atom#207]
I've been thinking about this for a while.
I just want to show my plan here and maybe get some advice/suggestions before making any change.

- [ ] Add feature descriptions (e.g. scopes and how to add more)
- [ ] List supported formats (by default)
- [ ] Explain "hidden" behaviors (e.g. using `prettier` from project dependencies)
- [ ] Review contributing guidelines
- [ ] Add table of contents and links to navigate back to top
- [ ] Add links to other documents (contributing guidelines, code of conduct)
- [ ] List ESLint rules that match Prettier options (for config tweaks)

**Comment by robwise** [comment]
I think we definitely should go into greater detail of how the different options interact with each other. We've had a lot of issues in the past where people didn't properly understand how various settings were getting chosen, especially regarding the eslint integration and which version of prettier gets used. At first, we didn't have this because it was simpler, but lots of people requested it, so we put it in, and now people are confused by it. I think it's nice to have, but you're right, it needs to be made more clear what is going on. 

We just need to make sure that people who want a really quick rundown of how to use the plugin aren't overwhelmed by the amount of information, so if we could somehow put the really quick rundown of what the plugin does and how to use it first, and then link to a different section for those wanting a deep dive, that would be great.

Also, "Add anchors for navigation" should automatically be done by GitHub's markdown parser if I'm not mistaken.

Contributing guidelines and code of conduct and all of that probably needs updating as .you say, I think a lot of that I just copied over from prettier-eslint and didn't really update it.

As far as feature descriptions, I almost feel that we should stick to modifying the config-schema.json descrptions so that it's DRY and so that people don't have to leave Atom to figure out how things work?

**Comment by robwise** [comment]
Oh also, it might be useful to list a mapping of the eslint rules to their prettier rules, so people know what rules to set in their eslint config

**Comment by darahak** [comment]
All great suggestions, thanks @robwise!

> Also, "Add anchors for navigation" should automatically be done by GitHub's markdown parser if I'm not mistaken.

I see what you're talking about, but I was referring to a table of contents and links that redirect to that table. I'll rephrase that item.

> As far as feature descriptions, I almost feel that we should stick to modifying the config-schema.json descrptions so that it's DRY and so that people don't have to leave Atom to figure out how things work?

I agree. Let's focus on being didactic and effective with a short "getting started" section.
Options will speak for themselves.

Although we should address some subtleties like the scopes being in `Format on Save` but applied on manual format too.

**Comment by olsonpm** [comment]
> We just need to make sure that people who want a really quick rundown

Do you think placing a run-down in the readme would help?  I'm assuming the number of settings for this plugin makes it unlikely people will scroll all the way down to the readme.  Maybe they would catch it upon installing or searching for the plugin though?  Or if there's a way to create a link at the top of the settings to a wiki page... I'm willing to put something together but I don't know where it would be most accessible/useful.

Also, my idea of a rundown would be a few high level use-cases like

**I want this plugin to**
- format code according to a project's preferences
    - *description of applicable options*
- format code according to my own preferences
    - ...
- integrate with other styling tools
    - ...

but I don't have any strong opinions.
<br>

> address some subtleties like the scopes being in Format on Save but applied on manual format too.
Could I push those all the way to the bottom?  They just seem like the least to be used of all the settings.
<br>

**Regarding documentation for how the integrated configs interact:**

Seems to me this repo can't tackle this problem.  Editorconfig and eslint for example don't have a single source of truth for documentation.  Editorconfig currently only has blurbs of what options get affected, but not how.  prettier-eslint is worse in that it [tells people to look at `src/utils.js`](https://github.com/prettier/prettier-eslint#inferring-prettieroptions-via-eslintconfig) haha.

Not that this is a bad thing because as I've learned from webpack and uglifyjs, very useful tools can be created which don't have the greatest documentation.  Not to mention they're free.  I just don't think this repo can expect to be user-friendly in that regard until upstream allows for it.

**Comment by robwise** [comment]
> Do you think placing a run-down in the readme would help? I'm assuming the number of settings for this plugin makes it unlikely people will scroll all the way down to the readme. 

The rundown would be for people haven't yet installed the package and therefore don't see any settings. It's so that people browsing for plugins to install can quickly determine what this is and whether they want to install it.

> Also, my idea of a rundown would be a few high level use-cases like

That seems more like an in-depth explanation, which would be cool but I think it should go below. We should have a quick, couple-sentence paragraph and a .gif, much like we have now (although I think the .gif I made is too big), just to explain to people what is going on.

> Could I push those all the way to the bottom? They just seem like the least to be used of all the settings and they take up a lot of space. 

You'd be surprised how many people have requested this stuff, but yes this is fine.

> remove the redundant Use Editor: Log Cursor Scope to determine the scopes for a file

We should keep this so people know how to find the scope of what document they're working in.

> Regarding documentation for how the integrated configs interact: Seems to me this repo can't tackle this problem

We could limit the explanation to simply explaining what _we_ do since we're at least in control of that. That would help a little bit. But again, this is for the more "deep dive" section as opposed to the top section.

**Comment by olsonpm** [comment]
thanks, i think i understand what you're looking for except how the rundown should look.  I'll create a PR for further feedback.
