### ISSUE TITLE
no-mixed-operators eslint rule not being respected

### ISSUE THREAD

**Issue by lifeiscontent** [prettier/prettier-atom#224]
when using prettier-atom with the rule http://eslint.org/docs/rules/no-mixed-operators

it removes the mixed operator formatting

this:

``` js
	x = x > 0.008856 ? Math.pow(x, 1 / 3) : (7.787 * x) + (16 / 116);
	y = y > 0.008856 ? Math.pow(y, 1 / 3) : (7.787 * y) + (16 / 116);
	z = z > 0.008856 ? Math.pow(z, 1 / 3) : (7.787 * z) + (16 / 116);
```

turns into this:

``` js
	x = x > 0.008856 ? Math.pow(x, 1 / 3) : 7.787 * x + 16 / 116;
	y = y > 0.008856 ? Math.pow(y, 1 / 3) : 7.787 * y + 16 / 116;
	z = z > 0.008856 ? Math.pow(z, 1 / 3) : 7.787 * z + 16 / 116;
```

**Comment by robwise** [comment]
@lifeiscontent This is just the atom integration. Prettier itself has no ability to switch this off, and because eslint can't autofix this, there's nothing we really can do on this repo. I would suggest either trying to get this to be eslint fixable or petitioning the prettier repo to make this an option. 

I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
