### ISSUE TITLE
support markdown from prettier 1.8

### ISSUE THREAD

**Issue by kentcdodds** [prettier/prettier-atom#303]
Hey folks! I'd love to get support for markdown from prettier 1.8. I did a little digging and I think that I found all the places that need a change:

1. [Around here we need another `if` statement](https://github.com/prettier/prettier-atom/blob/19523c42260b82cdfdda7994125bc8a2b3f16271/src/executePrettier/buildPrettierOptions.js#L58)
2. [Around here we need a `isCurrentScopeMarkdownScope`](https://github.com/prettier/prettier-atom/blob/19523c42260b82cdfdda7994125bc8a2b3f16271/src/editorInterface/index.js#L22) (and export that below)
3. [Around here we need a `getMarkdownScopes`](https://github.com/prettier/prettier-atom/blob/19523c42260b82cdfdda7994125bc8a2b3f16271/src/atomInterface/index.js#L41) (and add that to the export below and include it in `getAllScopes`).
4. [Around here we need a `markdownScopes`](https://github.com/prettier/prettier-atom/blob/c2f2f5cf2ae46d6307314eae9dc7e4891c46f65b/src/config-schema.json#L106) thing like the others.

I'm pretty sure that should do it. Anyone wanna take that?

**Comment by kentcdodds** [comment]
If you've never done atom plugin dev before, [this](https://github.com/blog/2231-building-your-first-atom-plugin) could help (and [the official guide](https://github.com/blog/2231-building-your-first-atom-plugin)).

**Comment by vivek12345** [comment]
@kentcdodds I have never done atom plugin dev before, am I still allowed to take this up?

**Comment by kentcdodds** [comment]
Absolutely! It'll be a learning experience for sure! Good luck!

Make sure to check the CONTRIBUTING.md file :+1:

**Comment by robwise** [comment]
And please make sure to add tests :)

**Comment by kentcdodds** [comment]
Definitely! Do you have a suggestion for where those should go @robwise?

**Comment by robwise** [comment]
Pretty much each file has its own corresponding test file, with the exception of `src/main.js`. We keep the test files right next to the source files (as opposed to inside a `__tests__` folder, although that probably would have been cleaner). It should hopefully be clear from glancing at those how and where to test what you added, as adding new language/parser support this is a pretty common pattern by now.

The only exception would be the `atomInterface` file since that's at the edge where we actually call to Atom, which doesn't exist so there's not really much to test, although you could.

**Comment by darahak** [comment]
We should add this information to [CONTRIBUTING.md](https://github.com/prettier/prettier-atom/blob/master/CONTRIBUTING.md).
