### ISSUE TITLE
Option to format on Open

### ISSUE THREAD

**Issue by brybrophy** [prettier/prettier-atom#319]
My team is using prettier to format everyone's code pre-commit. This gives each developer the freedom to format code in their development environment however they want, while making sure it is pretty before it gets pushed up.

The problem is that we then have to manually reformat files to match our local settings when we open them again. It would be great to have an option to automatically format files when the get opened.

**Comment by robwise** [comment]
Interesting, I've never heard of prettier being used this way. I suppose we could add a `formatOnOpen` option, but we'd need to make sure the file was an already-saved file otherwise we won't be able to look up things like the nearest package.json and such which we need to do. Would you be willing to make a PR?

**Comment by brybrophy** [comment]
Sorry I haven't replied to this in so long. Been very swamped with work. I will have some free time over the holiday and will try to get a PR put together.
