### ISSUE TITLE
Global Version of Prettier Not Resolved in Linux

### ISSUE THREAD

**Issue by robwise** [prettier/prettier-atom#448]
If a local version of Prettier is not found, prettier-atom is supposed to fall back to a global version if one is available. This does not work on Linux.

It's not showstopping because we can then further fall back to a bundled version that comes with prettier-atom, but it should be fixed.

Reported by @krugar

**Comment by krugar** [comment]
Sorry for the extra-late reply, but just to be more specific: This likely works on Linux if the global Node version is installed via the Linux distribution's package manager.

If however, one (also?) installs Node via [NVM](https://github.com/creationix/nvm), prettier-atom will not fall back onto a globally installed version of prettier, but the bundled one. This happens because the [global-prefix](https://github.com/jonschlinkert/global-prefix/) package that prettier-atom uses to figure out where to look for globally installed npm packages has no clue about NVM and where it puts things.

**Comment by kachkaev** [comment]
Seems like global prettier still does not get detected by `prettier-atom` in some environments. Our use case is macos + nvm. Until `global-prefix` is fixed (which might take quite some time), something as simple as this would probably work as a workaround:

https://github.com/prettier/prettier-atom/blob/fbce7e8beac582e215124858a8b05d70784f8fe3/src/helpers/getPrettierPath.js#L10-L11

↓

```ts
const getGlobalPrettierPath = (): ?FilePath =>
  findCached(globalModules, PRETTIER_INDEX_PATH) ||
  findCached(path.join(globalModules, 'lib'), PRETTIER_INDEX_PATH) ||
  findCached(yarnGlobalModules, PRETTIER_INDEX_PATH);
```

Adding lib as a fallback should help at lest for the NVM's case because `global-prefix` returns
`/Users/username/.nvm/versions/node/v12.11.1 `, while NVM's node modules are in
`/Users/username/.nvm/versions/node/v12.11.1/lib/node_modules`.

For now this is just a hypothesis based on some tests in a terminal, but I'm happy to finish the investigation and prepare a PR if it can be considered. Maintainers, WDYT?
