### ISSUE TITLE
Config from Atom package ignored

### ISSUE THREAD

**Issue by gaetanboedec** [prettier/prettier-atom#449]
Hello, Since the latest update of the package `0.55.2`, the package doesn't take into account the settings.

<details>
Atom version: 1.29.0
prettier-atom version: 0.55.2
prettier: bundled
prettier version: 1.13.4
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "excludedGlobs": [
      "package.json"
    ],
    "isDisabledIfNoConfigFile": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false
  },
  "prettierOptions": {
    "parser": "flow",
    "singleQuote": true,
    "trailingComma": "all"
  },
  "scopes": {},
  "useEslint": false,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
</details>

**Comment by vyrruss** [comment]
@robwise Ok thanks for the info, will do now.

**Comment by DavidTorrijos** [comment]
Really?? 😔

**Comment by robwise** [comment]
> I don't like to include a .prettierrc, I have more than 20 plugins and the configuration of all of them is inside Atom. Should I have a single configuration file per plugin? I don't think so...

It's standard practice for these types of plugins, yes. See basically every `linter-XXX` package in existence. Remember, you can place a global `.prettierrc` in your home directory and you will never have to worry about a `.prettierrc` file again if you don't want to.

> Is this a permanent solution?

Yes because it's unfortunately not possible to do it the old way and also support the features Prettier now has (specifically plugins and automated parser inference). My hand was forced, but I must admit, I think it's a positive change anyway (this repo is now much simpler and easier to understand).

**Comment by Siilwyn** [comment]
For people reading this that use the plugin to just clean up files once in a while for projects with no prettier or linting and don't want to add yet another dotfile to their home directory I found: [atom-miniprettier](https://github.com/duailibe/atom-miniprettier) which lets you put the options in the Atom config file.
