### ISSUE TITLE
No error messages

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier-atom#458]
Hello, when prettier is unable to format a file on save, I don't see any messages of any sort indicating the failure. 

It'd be nice to have an option to be able to see errors.

At the moment, if there's a syntax error, prettier just silently fails with no indication of anything.

**Comment by rixo** [comment]
For good measure, I have got the reverse problem: I get spammed with error notifications that originates in a prettier plugin.

According to [this comment](https://github.com/prettier/prettier-atom/issues/466#issuecomment-442168718) on another issue, I get that no notification is the current expected behaviour. However I very much get a notification.

The plugin in question is [prettier-plugin-eslint](https://github.com/UnwrittenFun/prettier-plugin-svelte). It is still in early development stage, but its error seems pretty legit to me. The plugin error comes from [here](https://github.com/UnwrittenFun/prettier-plugin-svelte/blob/master/src/print/index.ts#L384).

It is caught in `prettier-atom` [here](https://github.com/prettier/prettier-atom/blob/master/src/executePrettier/executePrettierOnBufferRange.js#L108).

Since, apparently, there isn't a consensus on whether there should be UI notifications or not, I would suggest adding an option to mute them.

IMO notifications should be enabled by default because otherwise normal expected formatting errors (at least those originating in some plugins) could be mistaken for malfunction of this package by new users.

Or if you want to go out of your way on this, you could add some indicator that the last prettier pass failed, in the status bar, alongside the "format on save" toggle label. But as far as I'm concerned, an option + console log would be far enough to make me happy.

**Comment by robwise** [comment]
Well the problem is that some of these plugins are AFAICT not conforming to the proper API. Any formatting error is supposed to just pipe through to the Atom `linter` package and show inline.

 If it's some other type of error, prettier-atom can't know ahead of time whether it's a show-stopping error or just a typical syntax error thing that the plugin is throwing with a malformed object structure.

Can you give an example of the type of error you are seeing?

You're right that it's gone back and forth a lot. Without them it fails silently and you have no idea it's not even working or why, and with them it can get spammy in certain situations.

**Comment by rixo** [comment]
What's the proper API in this case? For the plugins to catch their own errors and report them with the linter API? Or do you mean an error with a specific interface should be thrown? Is there anything documented?

Sorry, I didn't point to the right plugin, it's prettier-plugin-svelte, not eslint.

I've previously linked to the source of the error I'm getting. Visually, I just get a red toast with message "prettier-atom failed: undefined".

![Capture d'écran 2019-06-04 21:22:48](https://user-images.githubusercontent.com/1670419/58907970-aa201800-870f-11e9-95bf-92ea51d3a25c.png)

Anyway I think `prettier-atom` is already doing the right thing by catching the unruly error and not dying on it.

I think making error reporting optional is the easy way out of this. From what you say, there should probably be 2 options, one for disabling confidently identified syntax errors, and another to silence all other errors. And, as illustrated by the OP, I think both options should be off by default (meaning all errors visible) so that people can get a grasp at why their code is not formatting, and the general stability of their stack... Before they get fed with the error and disable them.

**Comment by robwise** [comment]
Basically any error that doesn't have any `message` property. You can see our error handling here: https://trello.com/c/rnUVDOCU/132-health-check-unexpectedwindingdownportfoliocompany

Usually there's a message, but sometimes we get these undefined ones and then we don't know what to do with them so we just pass through to an Atom notification.

I'd be open to having an option called "Silence all non-syntax errors" if we put some type of WARNING in the description of the option explaining that this is potentially dangerous and is merely for malfunctioning plugins.
