### ISSUE TITLE
Format on save not working for custom extension added with parser overrides

### ISSUE THREAD

**Issue by jeanfredrik** [prettier/prettier-atom#460]
I’ve added the PHP plugin (https://github.com/prettier/plugin-php) and it works great right out of the box for `*.php` files. I’m working with a Drupal project however and they’re using some other extensions for PHP files (`*.module` and `*.theme`), so I’ve added these lines to my `.prettierrc` file:

```yml
overrides:
  - files: ['*.module', '*.theme']
    options:
      parser: php
```

With this the `Prettier: Format` command is working as expected for these files, but the files are not automatically formated on save. How can I fix this?

<details>
<summary>Output of the `Prettier: Debug` command</summary>

```
Atom version: 1.32.2
prettier-atom version: 0.55.2
prettier: bundled
prettier version: 1.13.4
prettier-eslint version: 8.8.2
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "isDisabledIfNoConfigFile": true,
    "isDisabledIfNotInPackageJson": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "excludedGlobs": [],
    "whitelistedGlobs": []
  },
  "prettierOptions": {
    "printWidth": 80,
    "singleQuote": true,
    "trailingComma": "all"
  },
  "useEslint": false,
  "useStylelint": false,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

</details>

**Comment by robwise** [comment]
Sorry for the late response, this slipped by somehow.

prettier-atom determines whether to parse a file based on whether Prettier returns a parser when we call `prettier.getFileInfo.sync`. When I try to reproduce your scenario, Prettier is incorrectly returning that the `inferredParser` is `null`. 

You would need to make an issue over at Prettier itself and ask that they make it so that `getFileInfo` respects `overrides` in your config when determining what `inferredParser` to use.

**Comment by jeanfredrik** [comment]
No problem. I will make an issue over at Prettier instead. Thanks for the reply!
