### ISSUE TITLE
Formatting relies on file extension rather than set grammar

### ISSUE THREAD

**Issue by poacher2k** [prettier/prettier-atom#470]
As shown in this video:
![2018-11-29 10-12-51](https://user-images.githubusercontent.com/2255960/49211411-ca1cfa80-f3bf-11e8-8810-8910a708eacf.gif)
In video:
1. A JS file is turned into a pure object which prettier works well with
2. The grammar is changed to JSON
3. Prettier format is run, with no success
4. File extension is changed to .json
5. Prettier format is run, with success

Because of this, trying to format something in an unsaved file doesn't work either, and produces the error shown below
![image](https://user-images.githubusercontent.com/2255960/49210406-54b02a80-f3bd-11e8-88ff-8c7f9ea7cc49.png)

Expected result:
Prettier format should use the currently set grammar, instead of whatever the file extension is set to

**Comment by robwise** [comment]
Because of Prettier's addition of plugins, there's no way for prettier-atom to know whether Prettier is going to be able to format a file or not without asking Prettier first. So we can't just rely on Atom scopes (which we used to do).

In order to ask Prettier to tell us whether the file can be formatted, it must be saved to the hard drive (that's just how Prettier decided to write it).

So unfortunately, that means there's no way for prettier-atom to support formatting an unsaved file any longer.

**Comment by poacher2k** [comment]
Aw, that's unfortunate :\

This was a pretty useful feature for eg. working with JS in PHP - by just changing the grammar to html, prettier would format the JS.

**Comment by robwise** [comment]
I know, I was sort of in a "damned if you do, damned if you don't" situation (either give up what you described or not support the new "plugins" feature which people were requesting).

One light at the end of the tunnel might be some type of prettier plugin (or core feature) that is smart enough to do this itself in PHP.

**Comment by poacher2k** [comment]
I see! Will be crossing my fingers for that :]

Thank you for all your work on this plugin, I really appreciate it!
