### ISSUE TITLE
Prettier Button in Status Bar disappears on .html files

### ISSUE THREAD

**Issue by MiLeung** [prettier/prettier-atom#491]
Just uninstalled and reinstalled 0.56.4
![](https://media.giphy.com/media/5EOiIDmgChiMJ6pyxQ/giphy.gif)

**Comment by robwise** [comment]
@MiLeung I can't reproduce locally which tells me this either because your project is using an older version of prettier in its package.json, an older version of prettier that is globally installed, you have the file in your prettierignore, or you have blacklisted the file in your prettier-atom options.

**Comment by MiLeung** [comment]
This project has no package.json, prettier isn't installed globally, no prettierignore file, and don't see html files blacklisted in prettier-atom options. Beats me.
