### ISSUE TITLE
Settings are not respected since update 0.56.4

### ISSUE THREAD

**Issue by pstanton** [prettier/prettier-atom#497]
Since updating I've noticed that files being completely changed when they are saved - turns out my settings (particularly 'use tabs' and 'line length 140') are not being respected. instead i get horribly illegible code that uses roughly 1/5 of my screen width.

I do not have a `.prettierrc` or `.editorconfig` and `prettier` is not in my package.json.

> 
> Atom version: 1.28.1
> prettier-atom version: 0.56.4
> prettier: bundled
> prettier version: 1.15.2
> prettier-eslint version: 8.8.2
> prettier-atom configuration: {
>   "formatOnSaveOptions": {
>     "enabled": false,
>     "respectEslintignore": true,
>     "showInStatusBar": false,
>     "excludedGlobs": [],
>     "whitelistedGlobs": [],
>     "isDisabledIfNotInPackageJson": false,
>     "isDisabledIfNoConfigFile": false
>   },
>   "prettierEslintOptions": {
>     "prettierLast": true
>   },
>   "prettierOptions": {
>     "printWidth": 140,
>     "useTabs": true
>   },
>   "useEslint": false,
>   "useStylelint": false
> }
>

**Comment by robwise** [comment]
We've had to remove in-Atom settings because Prettier decided to go with `.prettierrc` config files and plugins which would not be possible with in-Atom settings. There is an Atom bug where settings that have been removed from the package do not properly disappear for users. So I think you're still seeing those prettier options in your Atom settings even though those no longer exist.

From now on, you will need to use a .prettierrc file. If you want to, you can just put it in your home folder so that you don't have to make a project-specific one.
