### ISSUE TITLE
Format on save for custom filetype/parser doesn't work

### ISSUE THREAD

**Issue by samselikoff** [prettier/prettier-atom#512]
I've been following work on the [Glimmer parser](https://github.com/jgwhite/prettier/issues/1) and I'm really stoked to start using it!

I tried out a recent version and I was able to format a template by manually invoking Prettier with control+option+F. But "Format on Save" is not working.

I also don't see the "Prettier ✅" status bar info on `.hbs` files. But the formatting does work, and I do see that status on my `.js` files.

Here's my `~/.prettierrc`:

```
{
  "overrides": [
    {
      "files": "**/*.hbs",
      "options": { "parser": "glimmer" }
    }
  ]
}
```

I even tried putting this into the root of my project, but still no dice.

Let me know if there's any more info I can provide! Really excited for this & thanks for all your work ❤️.

**Comment by robwise** [comment]
I can confirm. I think this is something that can be fixed. I think it may have something to do with this line I  just found in the API docs:

> Providing plugin paths in options.plugins (string[]) helps extract inferredParser for files that are not supported by Prettier core.

https://prettier.io/docs/en/api.html#prettiergetfileinfofilepath-options

Since we're not doing that, perhaps this is why things are going wrong?

However, I'm not sure how we're going to accomplish this. It's strange to me that Prettier doesn't just do this stuff automatically for us.

Basically what we do for inferring whether the file is formattable by Prettier is we call this `getFileInfo` function on the given file and Prettier is supposed to tell us whether or not that file is formattable by Prettier or not. 

So right now it's telling us that the file isn't formattable when it really is (it says `inferredParser: false`). Since you are specifically telling Prettier what the parser should be, there is no real reason IMO that Prettier shouldn't be able to return `glimmer` as the parser.

I think what needs to happen is that `getFileInfo` over on the Prettier repo needs to properly return the `inferredParser` if it's in the overrides. That should be a pretty simple change I would think. Can you make an issue over there?

**Comment by samselikoff** [comment]
Looks like this is already a duplicate of https://github.com/prettier/prettier-atom/issues/460, and Prettier already has the issue! https://github.com/prettier/prettier/issues/5566

**Comment by robwise** [comment]
Oh wow sorry, been a while since that one. Let's hope they get that fixed!

**Comment by samselikoff** [comment]
Trying to get it moving! https://github.com/prettier/prettier/pull/6361
