### ISSUE TITLE
does not work with PHP files without coercion 

### ISSUE THREAD

**Issue by kale1d0code** [prettier/prettier-atom#515]
The format on save functionality only seemed to work with file types like JavasSript and JSON. Opening files of these types, I can see the prettier indicator in my status bar to show format on save is active. 

When I open up a PHP file, this indicator disappears.
having a .prettierrc file in my project makes no difference.

After a few days playing around, I noticed that prettier and the php plugin must be installed as dependencies for my composer project for the plugin to format PHP files on save.

can this requirement be removed so that I can format PHP files with as much ease as JavaScript and JSON?

**Comment by robwise** [comment]
AFAIK, PHP is not natively supported by Prettier (it requires a Prettier plugin). Therefore, out-of-the-box Prettier is telling prettier-atom that it doesn't know how to handle PHP files so that's what prettier-atom reports. It's interesting that installing it locally seems to alleviate your problem as there used to be an issue where Prettier was not properly considering its plugins when reporting whether it was capable of formatting a file or not.

**Comment by robwise** [comment]
See also: https://github.com/prettier/prettier/issues/5566

**Comment by cinghaman** [comment]
> AFAIK, PHP is not natively supported by Prettier (it requires a Prettier plugin). Therefore, out-of-the-box Prettier is telling prettier-atom that it doesn't know how to handle PHP files so that's what prettier-atom reports. It's interesting that installing it locally seems to alleviate your problem as there used to be an issue where Prettier was not properly considering its plugins when reporting whether it was capable of formatting a file or not.

@robwise do you know what plugin addon is needed along with Prettier to run for PHP files?

**Comment by robwise** [comment]
Hmm, not off hand as it's not a language I code in, you might try over at the main prettier repo.
