### ISSUE TITLE
Select bin file from repo

### ISSUE THREAD

**Issue by note89** [prettier/prettier-atom#59]
When running this plugin you are stuck with the version bundled with the package. 
Would be great if one could use the version installed in `node_modules`.

Now i get a diff from running prettier via the command line and the atom package

**Comment by robwise** [comment]
Hmm, this is a great point. I am currently doing a big refactor but I will definitely plan on implementing this somehow.

**Comment by n1k0** [comment]
This is a really important point, as many different versions may existing across one's repositories.

**Comment by charypar** [comment]
@robwise Would you be interested in a PR making the change?

**Comment by robwise** [comment]
@charypar Sure! Do you want to take a stab at it? I figure we should prefer to look for the user's version of it first, and if we don't find it, then use our own packaged version. The only trick is that what you're looking for depends on whether they have the eslint integration turned on or not (look for `prettier` if not, look for `prettier-eslint` if so).

**Comment by charypar** [comment]
That was my thinking too. I'll have a look at the complexity around `prettier-eslint` and try to have a first stab at it by the end of this week. Thanks for the pointers!

**Comment by charypar** [comment]
@robwise I had a go and got it working using a dynamic `require`, but both eslint and flow are complaining about it and I'm thinking they are probably right - dynamic require does seem a bit iffy. 

Would it be better to switch to using prettier through its CLI (similar to how linter-eslint works)? Prettier-eslint doesn't have a CLI, but as far as I can tell, it already does a local lookup (https://github.com/prettier/prettier-eslint/blob/master/src/index.js#L45), so it should be possible to leave that as is.

I thought I'd ask your opinion before proceeding any further.

**Comment by robwise** [comment]
> Prettier-eslint doesn't have a CLI

@charypar It does, check this out: https://github.com/prettier/prettier-eslint-cli

> as far as I can tell, it already does a local lookup 

It looks like prettier-eslint does a local lookup of eslint and prettier, but do you think we should also do a local lookup of prettier-eslint itself?

> using a dynamic require, but both eslint and flow are complaining about it and I'm thinking they are probably right - dynamic require does seem a bit iffy.

Well, I'm thinking everyone is going to have the normal package installed, but not necessarily everyone will have the CLI installed? I was thinking we would recursively search up the file tree until we find a node_modules folder, and then check for it in there, and then call it? I think this is the require relative idea that you've done?

**Comment by n1k0** [comment]
> Well, I'm thinking everyone is going to have the normal package installed, but not necessarily everyone will have the CLI installed?

Maybe I'm misunderstanding what you're saying, but the prettier CLI is part of the npm package, typically available in `node_modules/.bin/prettier`. So if people are setting their Atom project root at the same level, it's just matter of calling it with `exec`.

We should also lookup for a global installation (`npm i -g`) of prettier as a fallback, which would be the result of `which prettier`, though I don't know how Atom deals with system user's `$PATH` (I remember it was a nightmare in Sublime).

**Comment by robwise** [comment]
> the prettier CLI is part of the npm package

Yeah but `prettier-eslint` and `prettier-eslint-cli` are separate.

> We should also lookup for a global installation (npm i -g) of prettier as a fallback, which would be the result of which prettier, though I don't know how Atom deals with system user's $PATH (I remember it was a nightmare in Sublime).

In this other issue people are wanting it to just turn itself off in this case:
https://github.com/jlongster/prettier-atom/issues/43

I'm not sure which we should go with here.

**Comment by n1k0** [comment]
> Yeah but prettier-eslint and prettier-eslint-cli are separate.

Ok I admittedly know nothing about these.

> I'm not sure which we should go with here.

I like their idea of checking for a prettier dependency in `package.json`. I could totally see an option in the settings to enable or disable autopicking. Best of both world?

**Comment by robwise** [comment]
Yeah I'd rather we have the option of what happens when we can't find prettier/prettier-eslint in your package.json. You can either use the version shipped with the plugin, or you can have nothing happen (and then drop the global concept)?

**Comment by n1k0** [comment]
It's easy saying as it's probably a bunch of work and a possible maintenance burden, but we could (should?) keep the current existing setup for people not having prettier installed at all.

**Comment by charypar** [comment]
I'd agree with @n1k0 we should keep the bundled prettier option, so that you get some formatting even on a clean project (or even static browser scripts with no npm). We could support the ask #43 as a config option, e.g. "Do nothing when there is no local Prettier" defaulting to false? 

I think using local prettier through the CLI route is probably generally a cleaner option: as @n1k0 pointed out, CLI comes bundled with prettier and it doesn't require a dynamic `require`, which could potentially leak memory (if you edit a lot of files in different projects) and may crash the plugin if not handled very carefully. 

In other news, I've confirmed that switching the ESlint support on actually prefers locally installed `prettier` over a bundled one, so there is actually nothing to be done about supporting this for `prettier-eslint` from my perspective, unless we see some potential issues with the package itself. I'd say that's unlikely - as far as I can tell `prettier-eslint` just stitches together the two tools, so there really shouldn't be any compatibility issues, I don't see people installing `prettier-eslint` in their projects anyway.

**Comment by robwise** [comment]
> "Do nothing when there is no local Prettier" defaulting to false?

I think we should try and avoid double negatives ("do nothing is false"). So I would word it as "Fallback to packaged version of prettier/prettier-eslint if no local module is found" or something to that effect.

> I don't see people installing prettier-eslint in their projects anyway.

I think we're making an assumption here. If we are going to have it work one way for prettier, we should have it work the same way for prettier-eslint. We do get bugs here all the time for prettier-eslint, so versioning does matter here.

Also, not to make it even more confusing, but also keep in mind we've had a request to fallback to normal prettier even with eslint integration checked if there is no eslintrc found. https://github.com/jlongster/prettier-atom/issues/71

**Comment by charypar** [comment]
Yes, sorry I didn't intend to suggest that as the actual copy :) "Fall back to packaged version" is much better.

What I was trying to point out with `prettier-eslint` is that I doubt people would install it in their project as a standalone tool to use in CI or git hooks and thus hit the problem of version mismatch between their scripts and Atom. That's how I understand this issue: your project has one version of prettier (because you want to use it in CI and for team members using editors that don't support integration) and Atom uses a different version. But of course you're right that it's an assumption. 

For what it's worth, I don't think commonly seeing bugs in prettier-eslint is evidence of people also using it directly in their projects, but happy to be proven wrong. 

Maybe together with #71 this is a case of dropping prettier-eslint and doing the "chaining" in prettier-atom? Or alternatively opening up prettier-eslint to allow 

1. Skipping either of the steps
2. Injecting fallback implementations of prettier and ESlint when local ones can't be found

That seems like a question of mid/long-term strategy though.

Coming back to the original question: for this incremental change, do you think we should call Prettier via it's CLI rather than dynamically require it, or is the dynamic require an ok approach for now?

**Comment by robwise** [comment]
> What I was trying to point out with prettier-eslint is that I doubt people would install it in their project as a standalone tool to use in CI or git hooks and thus hit the problem of version mismatch between their scripts and Atom.

I have two projects where I do exactly this (well, I use `prettier-eslint-cli` that is, not `prettier-eslint` directly). I'm not getting why you would do it for prettier but not prettier-eslint, they're the same use case?

> Coming back to the original question: for this incremental change, do you think we should call Prettier via it's CLI rather than dynamically require it, or is the dynamic require an ok approach for now?

Either approach is fine with me, although I'm not really clear on what the pros/cons are.

**Comment by charypar** [comment]
> I have two projects where I do exactly this (well, I use prettier-eslint-cli that is, not prettier-eslint directly).

Oh, ok, I stand corrected. That makes for an even more interesting challenge - finding a project local `prettier-eslint` or `prettier-eslint-cli`'s `prettier-eslint`. 

I suppose the question really is how likely is a version mismatch between bundled and local versions of those packages to give a different output vs. how likely are different prettier version. From my perspective `prettier-eslint` is quite simple, so apart from actual bugs (where I'd argue it's fine the user is just stuck waiting for an upgrade like with anything else), there isn't a huge space for versions to differ in behaviour, and thus it's not worth to complicate deciding which version to used. This is also my reason for the different treatment between it and prettier - unlike `prettier-eslint`, `prettier` will almost by definition evolve its formatting for some time. `prettier-eslint` seems "done" in the sense of features. 

Then again, all of the above are just my assumptions, which I'm basing on absolutely nothing but a gut feeling, so I'm happy to take your steer on it. 

Re the pros and cons, I can see the following, maybe there are others I missed:

solution | pros | cons 
---------|------|-----
CLI | can be statically analysed by Flow, unexpected problems with finding prettier won't cause crashes | slightly more complicated implementation - need to translate options to CLI flags
require | Simpler to implement | Can't be statically analysed (so Flow won't work), may result in requiring several instances of prettier in certain cases

**Comment by robwise** [comment]
@charypar Okay, good arguments. How about for now then, we go with your way and we don't worry about finding the prettier-eslint bin if the user is using the eslint integration. Then maybe at some point in the future, if we have enough reason, we can think about adding that.

Great table! If you're willing to do the CLI implementation, then it sounds superior to me. Thank you so much for your help!

**Comment by charypar** [comment]
Ok, let's do that. Maybe we could track looking up the other packages as separate issues and see if they get traction?

I'm happy to do the CLI implementation, I'll try and check back with a PR soon. Thanks for your patience getting to the bottom of this!

**Comment by robwise** [comment]
This is implemented in #104
